### ISSUE TITLE
Native exception on downscaling - video not sent afterwards

### ISSUE THREAD

**Issue by ceggert87** [twilio/video-quickstart-android#481]
### Description

Using H264 encoding and starting a video call with a full HD resolution in an environment and/or device that quickly causes downscaling, the encoder fails with a native exception (initEncode failed on MediaCodec.native_configure). Afterwards, no video will be sent anymore, but the camera is still visible for the Android device. Seems to be related to Qualcomm chips, as multiple devices with those have had this issue (e.g. Nexus 5X).

The downscaling goes as follows:
1920x1080 with rotation 0
1440x810 with rotation 0
960x540 with rotation 0
720x405 with rotation 0
-> Exception shortly after.

My current assumption is that the native part cannot deal with an uneven number in the resolution. The downscaling seems to be in alternating 3/4, 2/3 steps, so starting with 1920x1080 will inevitably lead to this on heavy downscaling. Starting with 720p seems to prevent the issue in this case, probably because the first resolution having an uneven number would be too low.

Removing any resolution that could lead to an uneven number at some point in the supportedFormats of the CameraCapturer via reflection seems to prevent these native issues, but I was hoping for a more...stable approach that would still enable full HD to be used as well. Alternatively a way to recognize this exception and restart the encoding process to send video content again.

Am I missing something regarding exception handling or the call setup by any chance that could help with this?

### Steps to Reproduce

1. Use a device that is able to send full HD videos
2. Use the following videoconstraints: maxVideoDimensions=1920x1080; minVideoDimensions=1920x1080;fps=30; aspectRatio=16:9
3. Establish a call and send video content with these constraints
4. Let the video downscale through any means until it reaches the 720x405 resolution (limit connectivity, shake device heavily, device throttling due to heat, whatever works in the environment)

#### Code

Can provide if needed, but since these are just basic settings the description should be enough?

#### Expected Behavior

Video downscales normally, everything works

#### Actual Behavior

A native exception happens shortly after the problematic resolution is reached (within 2 seconds), the video is not being sent anymore although the camera still renders on the Android client.  

#### Reproduces how Often

So far it seems to be 100%.

#### Logs

```
The Twilio logs look as follows (note that the client also received video content which also has shown a native exception, but is still working afterwards):

2020-03-03 11:37:17.383 1042-7587/com.example I/tvi.webrtc.Logging: CameraStatistics: Camera fps: 17.
2020-03-03 11:37:18.028 1042-7595/com.example I/tvi.webrtc.Logging: EglRenderer: Duration: 4002 ms. Frames received: 60. Dropped: 0. Rendered: 60. Render fps: 15.0. Average render time: 6242 μs. Average swapBuffer time: 3805 μs.
2020-03-03 11:37:18.201 1042-7593/com.example I/tvi.webrtc.Logging: EglRenderer: Duration: 4001 ms. Frames received: 73. Dropped: 0. Rendered: 73. Render fps: 18.2. Average render time: 10815 μs. Average swapBuffer time: 4415 μs.
2020-03-03 11:37:19.388 1042-7587/com.example I/tvi.webrtc.Logging: CameraStatistics: Camera fps: 18.
2020-03-03 11:37:21.406 1042-7587/com.example I/tvi.webrtc.Logging: CameraStatistics: Camera fps: 19.
2020-03-03 11:37:22.034 1042-7595/com.example I/tvi.webrtc.Logging: EglRenderer: Duration: 4006 ms. Frames received: 60. Dropped: 0. Rendered: 60. Render fps: 15.0. Average render time: 4673 μs. Average swapBuffer time: 2967 μs.
2020-03-03 11:37:22.202 1042-7593/com.example I/tvi.webrtc.Logging: EglRenderer: Duration: 4000 ms. Frames received: 75. Dropped: 0. Rendered: 75. Render fps: 18.7. Average render time: 11352 μs. Average swapBuffer time: 5079 μs.
2020-03-03 11:37:23.442 1042-7587/com.example I/tvi.webrtc.Logging: CameraStatistics: Camera fps: 19.
2020-03-03 11:37:25.473 1042-7587/com.example I/tvi.webrtc.Logging: CameraStatistics: Camera fps: 19.
2020-03-03 11:37:27.508 1042-7587/com.example I/tvi.webrtc.Logging: CameraStatistics: Camera fps: 19.
2020-03-03 11:37:29.534 1042-7587/com.example I/tvi.webrtc.Logging: CameraStatistics: Camera fps: 17.
2020-03-03 11:37:30.036 1042-7595/com.example I/tvi.webrtc.Logging: EglRenderer: Duration: 4001 ms. Frames received: 56. Dropped: 0. Rendered: 56. Render fps: 14.0. Average render time: 5330 μs. Average swapBuffer time: 3032 μs.
2020-03-03 11:37:30.205 1042-7593/com.example I/tvi.webrtc.Logging: EglRenderer: Duration: 4001 ms. Frames received: 72. Dropped: 0. Rendered: 72. Render fps: 18.0. Average render time: 11175 μs. Average swapBuffer time: 4639 μs.
2020-03-03 11:37:30.401 1042-7587/com.example I/tvi.webrtc.Logging: SurfaceEglRenderer: : Reporting frame resolution changed to 720x405 with rotation 0
2020-03-03 11:37:30.402 1042-7614/com.example I/tvi.webrtc.Logging: MediaCodecVideoEncoder: Java releaseEncoder
2020-03-03 11:37:30.404 1042-7821/com.example I/tvi.webrtc.Logging: MediaCodecVideoEncoder: Java releaseEncoder on release thread
2020-03-03 11:37:30.405 1042-1042/com.example I/tvi.webrtc.Logging: SurfaceViewRenderer: : onMeasure(). New size: 1816x1021
2020-03-03 11:37:30.405 1042-1042/com.example I/tvi.webrtc.Logging: SurfaceViewRenderer: : onMeasure(). New size: 1816x1021
2020-03-03 11:37:30.405 1042-1042/com.example I/tvi.webrtc.Logging: SurfaceViewRenderer: : onMeasure(). New size: 1816x1021
2020-03-03 11:37:30.405 1042-1042/com.example I/tvi.webrtc.Logging: SurfaceViewRenderer: : onMeasure(). New size: 1816x1021
2020-03-03 11:37:30.406 1042-1042/com.example I/tvi.webrtc.Logging: SurfaceViewRenderer: : onMeasure(). New size: 1728x972
2020-03-03 11:37:30.406 1042-1042/com.example I/tvi.webrtc.Logging: SurfaceViewRenderer: : onMeasure(). New size: 1728x972
2020-03-03 11:37:30.406 1042-1042/com.example I/tvi.webrtc.Logging: SurfaceViewRenderer: : onMeasure(). New size: 1728x972
2020-03-03 11:37:30.406 1042-1042/com.example I/tvi.webrtc.Logging: SurfaceViewRenderer: : onMeasure(). New size: 1728x972
2020-03-03 11:37:30.407 1042-1042/com.example I/tvi.webrtc.Logging: EglRenderer: setLayoutAspectRatio: 1.7777778
2020-03-03 11:37:30.407 1042-1042/com.example I/tvi.webrtc.Logging: SurfaceViewRenderer: : updateSurfaceSize. Layout size: 1728x972, frame size: 960x540, requested surface size: 960x540, old surface size: 960x540
2020-03-03 11:37:30.412 1042-1042/com.example I/tvi.webrtc.Logging: SurfaceViewRenderer: : updateSurfaceSize. Layout size: 1728x972, frame size: 720x405, requested surface size: 720x405, old surface size: 960x540
2020-03-03 11:37:30.421 1042-1042/com.example I/tvi.webrtc.Logging: SurfaceViewRenderer: : onMeasure(). New size: 1816x1021
2020-03-03 11:37:30.422 1042-1042/com.example I/tvi.webrtc.Logging: SurfaceViewRenderer: : onMeasure(). New size: 1816x1021
2020-03-03 11:37:30.422 1042-1042/com.example I/tvi.webrtc.Logging: SurfaceViewRenderer: : onMeasure(). New size: 1816x1021
2020-03-03 11:37:30.422 1042-1042/com.example I/tvi.webrtc.Logging: SurfaceViewRenderer: : onMeasure(). New size: 1816x1021
2020-03-03 11:37:30.423 1042-1042/com.example I/tvi.webrtc.Logging: SurfaceViewRenderer: : onMeasure(). New size: 1728x972
2020-03-03 11:37:30.423 1042-1042/com.example I/tvi.webrtc.Logging: SurfaceViewRenderer: : onMeasure(). New size: 1728x972
2020-03-03 11:37:30.423 1042-1042/com.example I/tvi.webrtc.Logging: SurfaceViewRenderer: : onMeasure(). New size: 1728x972
2020-03-03 11:37:30.423 1042-1042/com.example I/tvi.webrtc.Logging: SurfaceViewRenderer: : onMeasure(). New size: 1728x972
2020-03-03 11:37:30.425 1042-1042/com.example I/tvi.webrtc.Logging: SurfaceEglRenderer: : surfaceChanged: format: 4 size: 720x405
2020-03-03 11:37:30.426 1042-1042/com.example I/tvi.webrtc.Logging: EglRenderer: setLayoutAspectRatio: 1.7777778
2020-03-03 11:37:30.428 1042-1042/com.example I/tvi.webrtc.Logging: SurfaceViewRenderer: : updateSurfaceSize. Layout size: 1728x972, frame size: 720x405, requested surface size: 720x405, old surface size: 720x405
2020-03-03 11:37:30.472 1042-7821/com.example I/tvi.webrtc.Logging: MediaCodecVideoEncoder: Java releaseEncoder on release thread done
2020-03-03 11:37:30.473 1042-7614/com.example I/tvi.webrtc.Logging: MediaCodecVideoEncoder: Java releaseEncoder done
2020-03-03 11:37:30.473 1042-7614/com.example I/tvi.webrtc.Logging: MediaCodecVideoEncoder: Java initEncode: VIDEO_CODEC_H264. Profile: 0 : 720 x 405. @ 1700 kbps. Fps: 60. Encode from texture : true
2020-03-03 11:37:30.474 1042-7614/com.example W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
2020-03-03 11:37:30.483 1042-7614/com.example I/tvi.webrtc.Logging: MediaCodecVideoEncoder: Found target encoder for mime video/avc : OMX.qcom.video.encoder.avc. Color: 0x7f000789. Bitrate adjustment: NO_ADJUSTMENT
2020-03-03 11:37:30.483 1042-7614/com.example I/tvi.webrtc.Logging: MediaCodecVideoEncoder: Color format: 2130708361. Bitrate adjustment: NO_ADJUSTMENT. Key frame interval: 0 . Initial fps: 30
2020-03-03 11:37:30.484 1042-7614/com.example I/tvi.webrtc.Logging: MediaCodecVideoEncoder:   Format: {color-format=2130708361, i-frame-interval=20, mime=video/avc, width=720, bitrate-mode=2, bitrate=1700000, frame-rate=30, height=405}
2020-03-03 11:37:32.549 1042-7828/com.example E/tvi.webrtc.Logging: MediaCodecVideoDecoder: Media decoder release failed
2020-03-03 11:37:32.550 1042-7828/com.example E/tvi.webrtc.Logging: MediaCodecVideoDecoder: android.media.MediaCodec$CodecException: Error 0x80001009
2020-03-03 11:37:32.552 1042-7828/com.example E/tvi.webrtc.Logging: MediaCodecVideoDecoder: android.media.MediaCodec$CodecException: Error 0x80001009
        at android.media.MediaCodec.native_stop(Native Method)
        at android.media.MediaCodec.stop(MediaCodec.java:2067)
        at tvi.webrtc.MediaCodecVideoDecoder$1.run(MediaCodecVideoDecoder.java:429)
        at java.lang.Thread.run(Thread.java:764)
2020-03-03 11:37:32.553 1042-7414/com.example I/tvi.webrtc.Logging: SurfaceTextureHelper: stopListening()
2020-03-03 11:37:32.556 1042-7414/com.example I/tvi.webrtc.Logging: MediaCodecVideoDecoder: Java releaseDecoder done
2020-03-03 11:37:32.556 1042-7414/com.example I/tvi.webrtc.Logging: SurfaceTextureHelper: dispose()
2020-03-03 11:37:32.585 1042-7830/com.example I/tvi.webrtc.Logging: EglBase14: SDK version: 27. isEGL14Supported: true
2020-03-03 11:37:32.597 1042-7414/com.example I/tvi.webrtc.Logging: MediaCodecVideoDecoder: Trying to find HW decoder for mime video/avc
2020-03-03 11:37:32.597 1042-7414/com.example I/tvi.webrtc.Logging: MediaCodecVideoDecoder: Found candidate decoder OMX.qcom.video.decoder.avc
2020-03-03 11:37:32.600 1042-7414/com.example I/tvi.webrtc.Logging: MediaCodecVideoDecoder: Found target decoder OMX.qcom.video.decoder.avc. Color: 0x13
2020-03-03 11:37:32.600 1042-7414/com.example I/tvi.webrtc.Logging: MediaCodecVideoDecoder: Java initDecode: VIDEO_CODEC_H264 : 640 x 480. Color: 0x13. Use Surface: true
2020-03-03 11:37:32.604 1042-7830/com.example I/tvi.webrtc.Logging: SurfaceTextureHelper: Setting listener to tvi.webrtc.MediaCodecVideoDecoder$TextureListener@fbeb6a3
2020-03-03 11:37:32.607 1042-7414/com.example I/tvi.webrtc.Logging: MediaCodecVideoDecoder:   Format: {mime=video/avc, width=640, height=480}
2020-03-03 11:37:32.791 1042-7614/com.example E/tvi.webrtc.Logging: MediaCodecVideoEncoder: initEncode failed
2020-03-03 11:37:32.792 1042-7614/com.example E/tvi.webrtc.Logging: MediaCodecVideoEncoder: android.media.MediaCodec$CodecException: Error 0xfffffc0e
2020-03-03 11:37:32.797 1042-7614/com.example E/tvi.webrtc.Logging: MediaCodecVideoEncoder: android.media.MediaCodec$CodecException: Error 0xfffffc0e
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:1943)
        at android.media.MediaCodec.configure(MediaCodec.java:1872)
        at tvi.webrtc.MediaCodecVideoEncoder.initEncode(MediaCodecVideoEncoder.java:546)
2020-03-03 11:37:32.797 1042-7614/com.example I/tvi.webrtc.Logging: MediaCodecVideoEncoder: Java releaseEncoder
2020-03-03 11:37:32.802 1042-7841/com.example I/tvi.webrtc.Logging: MediaCodecVideoEncoder: Java releaseEncoder on release thread
2020-03-03 11:37:32.826 1042-7841/com.example I/tvi.webrtc.Logging: MediaCodecVideoEncoder: Java releaseEncoder on release thread done
2020-03-03 11:37:32.827 1042-7614/com.example I/tvi.webrtc.Logging: MediaCodecVideoEncoder: Java releaseEncoder done
```

#### Video Android SDK

5.1.0

#### Android API

API 29, API23 (probably more)

#### Android Device

LG Nexus 5X, Samsung Galaxy S10E

Thank you!

**Comment by aaalaniz** [comment]
Hey @ceggert87 

Thank you for the detailed description. As you mentioned, the issue described appears to be a hardware issue. We'll have a look through [WebRTC bugs](https://bugs.chromium.org/p/webrtc/issues/list) and see if this problem has been resolved in a future release of WebRTC.

Thanks again!

**Comment by Nuclominus** [comment]
Hello! Same problem. After few seconds video is no longer available. Stably repeated on nexus 5 with android 5 or 6. On the LG Nexus 5x with android 8.1.0, there is no problem, it was possibly fixed in OS part

**Comment by ceggert87** [comment]
@Nuclominus Sorry didn't see the reference at the end. I made something like this (just a basic example using the back camera):

`private void limitResolutions() {
        logger.debug("Limiting resolutions");
        try {
            //Get fields of the CameraCapturer
            final Field formatProviderField = cameraCapturer.getClass().getDeclaredField("formatProvider");
            formatProviderField.setAccessible(true);
            Object formatProvider = formatProviderField.get(cameraCapturer);

            final Class cameraCapturerFormatProviderClass = Class.forName("com.twilio.video.CameraCapturerFormatProvider");
            final Field supportedFormatsField = cameraCapturerFormatProviderClass.getDeclaredField("supportedFormatsMap");
            supportedFormatsField.setAccessible(true);

            this.supportedFormats = getSupportedFormats(getCameraId(CameraCapturer.CameraSource.BACK_CAMERA));

            Map<CameraCapturer.CameraSource, List<VideoFormat>> supportedFormatsMap =
                    new HashMap<>();
            supportedFormatsMap.put(CameraCapturer.CameraSource.BACK_CAMERA, this.supportedFormats);

            // Replace with our
            Object supportedFormats = supportedFormatsField.get(formatProvider);
            if (supportedFormats instanceof Map) {
                ((Map) supportedFormats).clear();
                ((Map) supportedFormats).putAll(supportedFormatsMap);
            }
            //supportedFormatsField.set(oldMap, supportedFormatsMap);
        } catch (Exception e) {
            logger.error("Failed to add Intel H264 support:", e);
        }
    }`

getSupportedFormats just goes through the camera parameters and throws out any preview size that could potentially lead to an uneven resolution assuming it goes down by 3/4, 2/3, 3/4, 2/3....

**Comment by aaalaniz** [comment]
Please validate this behavior still occurs in 6.0.0 and reopen if necessary thank you!
